services:
  db:
    image: postgres:12
    env_file: ${ENV_FILE:-.env}
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  med_base_api:
    image: diplom
    ports:
      - "8000:8000"
    volumes:
      - ./med_base_api:/src/med_base_api
    depends_on:
      db:
        condition: service_healthy
    command: med_base_api

  admin:
    image: diplom
    ports:
      - "8001:8501"
    volumes:
      - ./admin:/src/admin
    depends_on:
      - med_base_api

    command: admin
