"""Созданы таблицы

Revision ID: 7c636de94994
Revises: 
Create Date: 2025-03-18 23:12:19.705879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c636de94994'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Идентификатор медицинского термина'),
    sa.Column('name', sa.String(), nullable=False, comment='Название медицинского термина'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание медицинского термина'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Таблица с медицинскими терминами',
    info={'readable_name': 'Медицинский термин'}
    )
    op.create_index(op.f('ix_term_id'), 'term', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_term_id'), table_name='term')
    op.drop_table('term')
    # ### end Alembic commands ###
